- name: Download cirros
  get_url: url=http://download.cirros-cloud.net/0.3.5/cirros-0.3.5-x86_64-disk.img dest=/root/cirros.img
- name: Upload cirros image
  shell: openstack image create --disk-format qcow2 --container-format bare --public --file /root/cirros.img cirros
  environment: "{{ adminrc }}"
  ignore_errors: True
- name: Create m1.nano flavour
  shell: openstack flavor create --id 0 --vcpus 1 --ram 64 --disk 1 m1.nano
  environment: "{{ adminrc }}"
  ignore_errors: True
- name: Create icmp security group for demo user
  shell: openstack security group rule create --proto icmp default
  environment: "{{ demorc }}"
  ignore_errors: True
- name: Create tcp security group for demo user
  shell: openstack security group rule create --proto tcp --dst-port 22 default
  environment: "{{ demorc }}"
  ignore_errors: True
- debug:
    msg: "the current time is {{ ansible_date_time.time }}"
- name: Discover compute hosts
  shell: sh -c "nova-manage cell_v2 discover_hosts --verbose" nova
