# Self service
selfservice_gateway: 192.168.0.1
selfservice_cidr: 192.168.0.0/24

#Provider
start_provider_subnet_pool_ip: 10.10.65.50
end_provider_subnet_pool_ip: 10.10.65.55
provider_dns: 8.8.8.8
provider_gateway: 10.10.64.1
provider_subnet_cidr: 10.10.64.0/23




adminrc:
  OS_PROJECT_DOMAIN_NAME: Default
  OS_USER_DOMAIN_NAME: Default
  OS_PROJECT_NAME: admin
  OS_USERNAME: admin
  OS_PASSWORD: AD_PASS
  OS_AUTH_URL: http://controller:35357/v3
  OS_IDENTITY_API_VERSION: 3
  OS_IMAGE_API_VERSION: 2


demorc:
  OS_PROJECT_DOMAIN_NAME: Default
  OS_USER_DOMAIN_NAME: Default
  OS_PROJECT_NAME: demo
  OS_USERNAME: demo
  OS_PASSWORD: DM_PASS
  OS_AUTH_URL: http://controller:35357/v3
  OS_IDENTITY_API_VERSION: 3
  OS_IMAGE_API_VERSION: 2

