# Installing and configuring the components required for compute
# Environment
- name: Install NTP
  yum: name=chrony
- name: Copy chrony.conf
  template: src=../templates/chrony.conf dest=/etc/chrony.conf
- name: Start and Enable chrony
  systemd: name=chronyd.service enabled=True state=started
- name: Enable the OpenStack repository
  yum: name=centos-release-openstack-newton
- name: Upgrade the packages on your host
  yum: name="*" state=latest
- name: Install the OpenStack client
  yum: name={{ item }}            
  with_items:
    - python-openstackclient
    - openstack-selinux

# Compute
- name: Install nova packages
  yum: name=openstack-nova-compute
- name: Copy /etc/nova/nova.conf
  template: src=../templates/nova.conf dest=/etc/nova/nova.conf
- name: Check hardware acceleration
  shell: egrep -c '(vmx|svm)' /proc/cpuinfo
  register: hwacc
- name: Edit libvirt in nova.conf
  blockinfile:
    dest: /etc/nova/nova.conf
    insertafter: "libvirt"
    block: |
      virt_type = kvm
  when: hwacc.stdout > 0
- name: Start and Enable Nova services
  systemd: name={{ item }} enable=yes state=started
  with_items:
    - libvirtd.service
    - openstack-nova-compute.service


# Network
- name: Install packages
  yum: name={{ item }}
  with_items:
    - openstack-neutron-linuxbridge
    - ebtables
    - ipset
- name: Copy /etc/neutron/neutron.conf
  template: src=../templates/neutron.conf dest=/etc/neutron/neutron.conf

# Networking option 2 ( Self - Service Networks)
- name: Copy /etc/neutron/plugins/ml2/linuxbridge_agent.ini
  template: src=../templates/linuxbridge_agent.ini dest=/etc/neutron/plugins/ml2/linuxbridge_agent.ini
- name:  Configure Nova (/etc/nova/nova.conf) to use Neutron
  template: src=../templates/nova.conf dest=/etc/nova/nova.conf)    #################
- name: Restart the Compute service
  systemd: name=openstack-nova-compute.service state=restarted
- name: Enable and start services
  systemd: name=neutron-linuxbridge-agent.service enabled=yes state=started

